name: Node CI

on: [push]

jobs:
  unit-test:
    name: Build and Test Frontend Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci
      
      - name: Lint checking
        run: npm run lint
      
      - name: Source building
        run: npm run build
