name: Node CI

on: [push]

jobs:
  unit-test:
    name: Build and Test Frontend Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci
      
      - name: Lint checking
        run: npm run lint
      
      - name: Components testing
        run: npm run test

      - name: Source building
        run: npm run build
  notify-pull-request:
    name: Pull request created notify push on Slack
    runs-on: ubuntu-latest
    needs: [unit-test]
    if: ${{ github.base_ref == 'main' && github.event_name == 'pull_request' }}
    steps:
      - uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{\"channel\":\"${{ secrets.SLACK_PR_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Contributor :* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}' 

        if: success()
